### ISSUE TITLE
Minor Error in Store/File.php

### ISSUE THREAD

**Issue by cigamit** [GlimpseArchive/Glimpse.PHP#1]
Warning: fopen(/tmpglimpsestore00ced641b4de1a0f1cda13f734323dfa): failed to open stream: Permission denied in phar:///var/www/html/glimpse.phar/Glimpse/Store/File.php on line 26

PHP 5.3 running on Centos 5
Temp directory is /tmp

Line of code that causes the issue /Glimpse/Store/File.php on Line 14
            $fileName = sys_get_temp_dir() . 'glimpsestore' . md5(**FILE**);

Probably should check to see if the tmp directory ends in / (or \ on Windows) and append it if not.  You could also pair it with tempnam()

**Comment by maartenba** [comment]
Fixing it right away :-)
