### ISSUE TITLE
Failed opening 'phar:.../glimpse.phar/index.php' for inclusion

### ISSUE THREAD

**Issue by mahomedalid** [GlimpseArchive/Glimpse.PHP#3]
I don't know what I'm doing wrong, the samples of glimpse works, but when I tried to include it from another working system (located in /var/www/openbizDhcl/dhcl/bin/controller.php) this is what is happening:

Warning: include() [function.include]: Failed opening 'phar:///var/www/library/glimpse/Glimpse.PHP/build/glimpse.phar/index.php' for inclusion (include_path='phar:///var/www/library/glimpse/Glimpse.PHP/build/glimpse.phar:.:/usr/share/php:/usr/share/pear') in /var/www/library/glimpse/Glimpse.PHP/build/glimpse.phar on line 9

This is my php version:

PHP Version 5.3.3-1ubuntu9.5

I downloaded glimpse by git clone, today.

BTW, if I tried to include source/index.php it messed up my other autoloaders.

**Comment by maartenba** [comment]
Is the phar file stream wrapper registered? Can you try including the phar file using a relative path? What are you seeing with the autoloaders?

**Comment by mahomedalid** [comment]
Yes, the phar file stream is registered. Including using a relative phat is the same.

<?PHP
include_once("glimpse/Glimpse.PHP/build/glimpse.phar");
include_once("app.inc");
include_once(OPENBIZ_BIN."BizController.php");

Warning: include() [function.include]: Failed opening 'phar:///var/www/openbizDhcl/dhcl/bin/glimpse/Glimpse.PHP/build/glimpse.phar/index.php' for inclusion

**Comment by maartenba** [comment]
Is there an option to have a copy of your app (I'll gladly provide you my e-mail address so no one else has the opportunity to lok at your code)?

-----Original Message-----
